name: block commits touching certain files
on: 
  push:
    branches:
      - 'test-workflow' 
      - 'develop' # 'main' for RPL
  workflow_dispatch: #allow manual run
  workflow_call:
    

jobs:
  check-commits:
    name: List files touched this commit
    runs-on: ubuntu-latest
    #runs-on: [ P-10BLD03-V ] #Ask someone in devops or maybe Scott if this is correct. Ripped from ORION22-R3/.github/workflows/Do Build.yml
    outputs:
      ref_before: ${{ steps.step1.outputs.ref_before }}
      ref_after: ${{ steps.step1.outputs.ref_after }}
      changed_files: ${{ steps.step3.outputs.changed_files }}
    steps:
      - id: step1
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "finding refs..."
          before=$(echo "$GITHUB_CONTEXT" | jq -r '.event.before')
          after=$(echo "$GITHUB_CONTEXT" | jq -r '.event.after')
          echo "$before, $after"
          echo "trying to set outputs..."
          echo "ref_before=$before" >> $GITHUB_OUTPUT
          echo "ref_after=$after" >> $GITHUB_OUTPUT
#      - id: step2
#        run: |
#          echo "ref_before_push=$(jq -r '.event.before')"
#          echo "ref_after_push=$(jq -r '.event.after')"
#          git log --pretty=oneline "$ref_before_push...$ref_after_push" | wc -l
      - id: step3
        run: | #echo multiline string into $GITHUB_OUTPUT
          api_response=$(gh api /repos/swannobi/Red-DiscordBot/commits/1cd5f7247711437844fe234e2c94a090dab8aa82 --jq .files[].filename)
          echo "got from API: $api_response"
          echo 'changed_files<<EOF' >> $GITHUB_OUTPUT
          echo "$api_response" >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
  check-files-against-blocklist:
    name: Check if any files are sensitive
    runs-on: ubuntu-latest
    #runs-on: [ P-10BLD03-V ] #Ask someone in devops or maybe Scott if this is correct. Ripped from ORION22-R3/.github/workflows/Do Build.yml
    needs: check-commits
    steps:
      - id: step1
        env:
          SENSITIVE_FILES: |
            notpresent.py
            nope.py
            doesntexist.py
          changed_files: ${{ needs.check-commits.outputs.changed_files }}
          before: ${{ needs.check-commits.outputs.ref_before }}
          after: ${{ needs.check-commits.outputs.ref_after }}
        run: |
          echo "inputs:"
          echo "$changed_files"
          echo "before = $before"
          echo "after = $after"
          file_is_present=0
          
          declare -a changed_files_array
          declare -a sensitive_files_array

          echo "reading multiline strings into arrays..." #use process substitution < <(...) instead of a here-string <<< to avoid extra newline
          while read -r line; do
            sensitive_files_array+=("$line")
          done < <(printf '%s' "$SENSITIVE_FILES")
          
          while read -r line; do
            changed_files_array+=("$line")
          done < <(printf '%s' "$changed_files")

          for changed in "${changed_files_array[@]}"; do
            for pci_file in "${sensitive_files_array[@]}"; do
              echo "${pci_file} in ${changed} ?\n"
              if [[ ${changed} =~ ${pci_file} ]]; then 
                file_is_present=1
                echo "found!"
                break
              fi
            done
            if [ $file_is_present -eq 1 ]; then break; fi;
          done
          if [ $file_is_present -eq 1 ]; then
            echo "do something based on file being present"
          else
            echo "do something (or nothing) based on file not being present"
          fi
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} #Required by the GitHub CLI
